title: Example Title! # name of the site
author: Authorrrrr # name of site's author
url: https://example.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.
remote_theme: nerdvibe/no-style-please
kramdown:
  parse_block_html: true

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  show_description: false # show blog description in home page
